@better_submitter_api_HostAddress = http://localhost:5239

GET {{better_submitter_api_HostAddress}}/hello
Accept: application/json
###
GET {{better_submitter_api_HostAddress}}/student/?studentId=UG/19/0630
Accept: application/json
###

GET {{better_submitter_api_HostAddress}}/student/?studentId=UG/19/0630&assignmentType=Python
Accept: application/json
###

POST {{better_submitter_api_HostAddress}}/student
Content-Type: application/json
Accept: application/json

{
  "StudentId": "",
  "Department": "Mechanical",
  "Surname": "Gboun",
  "Firstname": "Marvellous",
  "Middlename": "Emmanuel"
}

###


PUT {{better_submitter_api_HostAddress}}/student/?studentId=UG/19/0760
Content-Type: application/json
Accept: application/json

{
  "StudentId": "UG/19/0760",
  "Department": 3,
  "Surname": "Gboun",
  "Firstname": "Marvlous",
  "Middlename": "Emmanuel"
}

###
