name: Better-Submitter Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH access
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          known_hosts: null

      - name: SSH into VPS, stop service, pull latest changes, restore and restart app
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ubuntu@${{ secrets.VPS_IP_ADDRESS }} << 'EOF'
            # Stop the service
            sudo systemctl stop better-submitter-api

            # Navigate to the project directory
            cd /home/ubuntu/better-submitter-api

            # Pull the latest changes
            git pull origin main

            # Restore dependencies
            dotnet restore

            # Restart the service
            sudo systemctl start better-submitter-api
          EOF
